version: '3.3'
services:

  discovery-server:
    image: chava12345/arquitectura-discovery-server-patterns:0.0.1-snapshot
    ports:
      - 8761:8761


  gateway-server-:
    image: chava12345/arquitectura-gateway-patterns:0.0.1-snapshot
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    ports:
      - 8766:8766

  postgres:
    build: servicesData/postgresdb/
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - ./blockstorage/postgres:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.6.12-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"

  api-users:
      image: chava12345/api-login-patterns:0.0.1-snapshot
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/red_social_login
        - SPRING_DATASOURCE_USERNAME=admin
        - SPRING_DATASOURCE_PASSWORD=admin
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
        - SPRING_BOOT_ADMIN_URL=http://monitor:8090
        - SPRING_RABBITMQ_HOST=rabbitmq
      ports:
        - "8084:8084"
      depends_on:
        - postgres
        - rabbitmq

  api-personas:
    image: chava12345/api-login-patterns:0.0.1-snapshot
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/red_social_personas
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_BOOT_ADMIN_URL=http://monitor:8090
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - rabbitmq






